# Generated by Django 6.0.6 on 2026-07-09 14:20

import validators.phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[validators.phone_number.PhoneNumberValidator()], verbose_name='Телефон'),
        ),
    ]
