
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    image: web:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - venv/
            - db_data/
            - db_data/**
        - action: rebuild
          path: ./requirements.txt
        - action: rebuild
          path: ./entrypoint.sh
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: cosmetic_db
    image: postgres:18.0-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/18/docker/
  rabbit_mq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  dbbrowser:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - db
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Kyiv
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery:1.0.0
    container_name: celery
    command: celery -A settings worker -l info
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - venv/
            - db_data/
        - action: rebuild
          path: ./requirements.txt
        - action: rebuild
          path: ./entrypoint.sh
    depends_on:
      - rabbit_mq

volumes:
  db_data: