# Generated by Django 6.0.6 on 2026-06-30 07:15

import validators.phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('name', models.CharField(max_length=256, verbose_name='Ім`я')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=19, validators=[validators.phone_number.PhoneNumberValidator()], verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('consultation', 'Консультація щодо підбору догляду'), ('question', 'Питання щодо замовлення чи доставки'), ('suggestion', 'Пропозиція про співпрацю'), ('other', 'Інше питання')], max_length=12, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name': 'Зворотній зв`язок',
                'verbose_name_plural': 'Зворотній зв`язок',
                'ordering': ['-created'],
            },
        ),
    ]
