# Generated by Django 6.0.6 on 2026-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В обробці'), ('waiting', 'Очікує відповіді клієнта'), ('resolved', 'Вирішено'), ('spam', 'Спам / Помилкове'), ('closed', 'Закрито без вирішення')], default='new', max_length=20, verbose_name='Статус обробки'),
        ),
    ]
