# Generated by Django 6.0.6 on 2026-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('consultation', 'Консультація щодо підбору догляду'), ('question', 'Питання щодо замовлення чи доставки'), ('suggestion', 'Пропозиція про співпрацю'), ('other', 'Інше питання')], default='consultation', max_length=12, verbose_name='Тема'),
        ),
    ]
