# Generated by Django 6.0.6 on 2026-06-26 10:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAndPayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Оплата та доствака',
                'verbose_name_plural': 'Оплата та доствака',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Політика конфіденційності',
                'verbose_name_plural': 'Політика конфіденційності',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Повернення та обмін',
                'verbose_name_plural': 'Повернення та обмін',
            },
        ),
    ]
