# Generated by Django 6.0.6 on 2026-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryandpaypolicy',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок'),
        ),
    ]
