# Generated by Django 6.0.6 on 2026-06-28 15:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_deliveryandpaypolicy_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Публічна оферта',
                'verbose_name_plural': 'Публічна оферта',
            },
        ),
    ]
