# Generated by Django 6.0.6 on 2026-07-06 10:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_publicoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryandpaypolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='publicoffer',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Текст документа'),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Текст документа'),
        ),
    ]
