upstream app {
    server web:8000;
}


server {
    listen 80;
    server_name localhost www.mycosmetic.ua mycosmetic.ua;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    ssl_certificate /app/ssl/mycosmetic.crt;
    ssl_certificate_key /app/ssl/mycosmetic.key;
    server_name localhost www.mycosmetic.ua mycosmetic.ua; #server_name www.yourdomain.com www.yourdomain2.com;



    error_log stderr warn;
    access_log /dev/stdout main;

    location / {
        proxy_pass http://app;
        # Добавляет заголовок (в header запроса) X-Forwarded-For с IP-адресом клиента,
        # который сделал первоначальный запрос.
        # Этот заголовок используется для определения исходного IP-адреса клиента.
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Устанавливает заголовок Host для проксируемых запросов с именем хоста, указанным клиентом.
        proxy_set_header Host $host;
        # Устанавливает заголовок X-Forwarded-Proto, указывающий, использовался HTTP или HTTPS.
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Real-IP $remote_addr;

        # Отключает автоматическое переписывание ответов с редиректами.
        proxy_redirect off;
    }

    location /static/ {
        # Запросы к /static/ будут обслуживаться из директории /app/static/.
        alias /app/static/;

        expires 30d;
        # Добавляет заголовок Cache-Control к ответам,
        # что ответ можно кэшировать публично и что его не следует модифицировать.
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}