# Generated by Django 6.0.6 on 2026-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Назва сайту', max_length=255, verbose_name='Назва сайту')),
                ('short_description', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Короткий опис')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
                ('slogan', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Гасло')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Конфігурація сайту',
            },
        ),
    ]
