# Generated by Django 6.0.6 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_strip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Догляд, що повертає шкірі сяйво', max_length=50, verbose_name='Заголовок (великий)')),
                ('subtitle', models.CharField(default='Краса доступна кожному', max_length=35, verbose_name='Заголовок (маленький)')),
                ('short_description', models.CharField(blank=True, default=None, max_length=125, null=True, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Картинка')),
                ('badge_title', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Заголовок (бейдж)')),
                ('badge_value', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Значення (бейдж)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Hero секція',
            },
        ),
    ]
