# Generated by Django 6.0.6 on 2026-06-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='in_footer',
            field=models.BooleanField(default=True, verbose_name='Показувати в футері'),
        ),
        migrations.AddField(
            model_name='phone',
            name='in_footer',
            field=models.BooleanField(default=True, verbose_name='Показувати в футері'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(max_length=254, verbose_name='Соціальна мережа')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('in_footer', models.BooleanField(default=True, verbose_name='Показувати в футері')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='main.siteconfig')),
            ],
            options={
                'verbose_name': 'Соціальна мережа',
                'verbose_name_plural': 'Соціальні мережі',
            },
        ),
    ]
