# Generated by Django 6.0.6 on 2026-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_email_in_footer_phone_in_footer_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Соціальну мережу', 'verbose_name_plural': 'Соціальні мережі'},
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Соціальна мережа'),
        ),
    ]
