# Generated by Django 6.0.6 on 2026-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_social_options_alter_social_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon', verbose_name='Фавіконка'),
        ),
    ]
