# Generated by Django 6.0.6 on 2026-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_siteconfig_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='slogan_top',
            field=models.CharField(blank=True, default=None, help_text='Слоган відображаєсться в на головній в заголовку.', max_length=512, null=True, verbose_name='Гасло'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Фавіконка', null=True, upload_to='favicon', verbose_name='Фавіконка'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип', null=True, upload_to='logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='short_description',
            field=models.CharField(blank=True, default=None, help_text='Короткий опис для SEO', max_length=512, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='slogan',
            field=models.CharField(blank=True, default=None, help_text='Слоган відображаєсться в футері', max_length=512, null=True, verbose_name='Гасло'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='title',
            field=models.CharField(default='Назва сайту', help_text='Назва сайту', max_length=255, verbose_name='Назва сайту'),
        ),
    ]
