# Generated by Django 6.0.6 on 2026-06-22 17:13

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_siteconfig_slogan_top_alter_siteconfig_favicon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="phone",
            field=models.CharField(
                max_length=19,
                validators=[validators.PhoneNumberValidator()],
                verbose_name="Телефон",
            ),
        ),
    ]
