# Generated by Django 6.0.6 on 2026-06-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_phone_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='title',
        ),
        migrations.AddField(
            model_name='social',
            name='social',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='telegram', max_length=10, verbose_name='Соціальна мережа'),
        ),
    ]
