# Generated by Django 6.0.6 on 2026-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_social_title_social_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адресс',
                'verbose_name_plural': 'Адресу',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=512, verbose_name='Графік')),
            ],
            options={
                'verbose_name': 'Графік роботи',
                'verbose_name_plural': 'Графік роботи',
            },
        ),
    ]
