# Generated by Django 6.0.6 on 2026-06-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_address_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='main.siteconfig'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='main.siteconfig'),
        ),
    ]
