# Generated by Django 6.0.6 on 2026-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_address_config_workschedule_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='copyright',
            field=models.CharField(blank=True, default=None, help_text='Копірайт відображаєсться в футері.', max_length=512, null=True, verbose_name='Копірайт'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_extend',
            field=models.CharField(blank=True, default=None, help_text='Додатковий копірайт відображаєсться в футері біля основного копірайта.', max_length=512, null=True, verbose_name='Додатковий копірайт'),
        ),
    ]
