# Generated by Django 6.0.6 on 2026-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_siteconfig_copyright_siteconfig_copyright_extend'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(default='manage@example.com', help_text='Email на який будуть присилатися листи з замовленнями та іншими повідомленями', max_length=254, verbose_name='Email'),
        ),
    ]
