# Generated by Django 6.0.6 on 2026-07-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_siteconfig_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='short_description',
        ),
    ]
