# Generated by Django 6.0.6 on 2026-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_siteconfig_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Слоган відображаєсться в футері', max_length=512, null=True, verbose_name='Гасло'),
        ),
    ]
