# Generated by Django 6.0.6 on 2026-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('slug', models.SlugField(max_length=256, verbose_name='Слаг')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Назва категорії')),
                ('short_description', models.CharField(max_length=25, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'ordering': ['-name'],
            },
        ),
    ]
