# Generated by Django 6.0.6 on 2026-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Показувати в хедері і футері'),
        ),
    ]
