# Generated by Django 6.0.6 on 2026-06-11 14:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_characteristicitem_characteristic_product_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='method_apply',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=None, null=True, verbose_name='Спосіб застосування'),
        ),
    ]
