# Generated by Django 6.0.6 on 2026-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_method_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'ordering': ['item'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Склад'),
        ),
    ]
