# Generated by Django 6.0.6 on 2026-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_characteristic_options_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Відображаються на головній сторінці в розділі "Улюбленці покупців" і позначаються бейджом "Хіт".', verbose_name='Хіт продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Відображаються на головній сторінці в розділі "Щойно з`явилися" і позначаються бейджом "Новинка".', verbose_name='Новинка'),
        ),
    ]
