# Generated by Django 6.0.6 on 2026-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_product_is_bestseller_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Відображаються на головній сторінці в розділі "Щойно з`явилися" і позначаються бейджом "Новинка".', verbose_name='Новинка'),
        ),
    ]
