# Generated by Django 6.0.6 on 2026-06-14 13:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_alter_product_is_new"),
    ]

    operations = [TrigramExtension()]
