# Generated by Django 6.0.6 on 2026-06-14 14:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20260614_1335'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='goods_produ_title_ded5a4_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='product_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='product_desc_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
