# Generated by Django 6.0.6 on 2026-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_product_goods_produ_title_ded5a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, help_text="Відображається на сторінці детальної інформації в розділі 'Переваги.'", verbose_name='Активні рослинні компоненти'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False, help_text="Відображається на сторінці детальної інформації в розділі 'Переваги.'", verbose_name='Доставка по всій Україні 1–3 дні'),
        ),
        migrations.AddField(
            model_name='product',
            name='derma',
            field=models.BooleanField(default=False, help_text="Відображається на сторінці детальної інформації в розділі 'Переваги.'", verbose_name='Дерматологічно протестовано'),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan_frendly',
            field=models.BooleanField(default=False, help_text="Відображається на сторінці детальної інформації в розділі 'Переваги.'", verbose_name='Vegan friendly, без жорстокості'),
        ),
    ]
