# Generated by Django 6.0.6 on 2026-07-02 12:57

import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('/', 'Головна сторінка'), ('/catalog/', 'Каталог'), ('/pages/contact/', 'Контакти')], help_text='Виберіть сторінку, до якої хочете налаштувати SEO', max_length=100, unique=True, verbose_name='Сторінка сайту')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (Title)')),
                ('description', models.TextField(blank=True, verbose_name='Опис (Description)')),
                ('keywords', models.CharField(blank=True, help_text='Введіть ключові слова через кому', max_length=255, verbose_name='Ключові слова')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo_images/', verbose_name='OG Зображення')),
            ],
            options={
                'verbose_name': 'SEO для статичної сторінки',
                'verbose_name_plural': 'SEO для статичних сторінок',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
