# Generated by Django 6.0.6 on 2026-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='page_type',
            field=models.CharField(choices=[('/', 'Головна сторінка'), ('/catalog/', 'Каталог'), ('/pages/contact/', 'Контакти'), ('/pages/privacy/', 'Політика конфіденційності'), ('/pages/return/', 'Обмін та повернення'), ('/pages/public/', 'Публічна оферта'), ('/pages/delivery/', 'Оплата і доставка')], help_text='Виберіть сторінку, до якої хочете налаштувати SEO', max_length=100, unique=True, verbose_name='Сторінка сайту'),
        ),
    ]
