# Generated by Django 6.0.6 on 2026-06-23 12:16

import django.db.models.deletion
import validators.phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_product_active_product_delivery_product_derma_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва способу оплати')),
                ('short_description', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Короткий опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Спосіб оплати',
                'verbose_name_plural': 'Способи оплати',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ['title'], 'verbose_name': 'Спосіб доставки', 'verbose_name_plural': 'Способи доставки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Закази'},
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Test', max_length=128, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='test', max_length=512, verbose_name='Адреса доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.deliverymethod', verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=256, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=256, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=19, validators=[validators.phone_number.PhoneNumberValidator()], verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новe'), ('in_progress', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('completed', 'Виконано'), ('canceled', 'Відмінено')], default='new', max_length=11, verbose_name='Статус замовлення'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='goods.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказаний продукт',
                'verbose_name_plural': 'Заказані продукти',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymentmethod', verbose_name='Спосіб оплати'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='order_order_created_708daa_idx'),
        ),
    ]
