# Generated by Django 6.0.6 on 2026-06-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_options_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
